### ISSUE TITLE
Potentially incorrect yaml behavior?

### ISSUE THREAD

**Issue by max-sixty** [stkb/Rewrap#257]
Thank you for such an excellent extension! It makes writing in VSCode much easier!

Is this correct behavior in YAML?

So far so good:

```yaml
two:
  houses:
    both:
      alike: |
        in dignity in fair verona where we lay our scene. From ancient grudge
```

But on the next work, it wraps:

```yaml
two:
  houses:
    both:
      alike: |
        in dignity in fair verona where we lay our scene. From ancient grudge
        breaks 
```

The `|` retains line breaks in yaml, and so putting `breaks` on a new line is semantically different from keeping it on the same line.
